// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebUygulamaProje1.Utility;

#nullable disable

namespace WebUygulamaProje1.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230828091131_reinstallvt")]
    partial class reinstallvt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebUygulamaProje1.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Fiyat")
                        .HasColumnType("double precision");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KitapTuruId")
                        .HasColumnType("integer");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KitapTuruId");

                    b.ToTable("kitaplar");
                });

            modelBuilder.Entity("WebUygulamaProje1.Models.KitapTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("kitap_turleri");
                });

            modelBuilder.Entity("WebUygulamaProje1.Models.Kitap", b =>
                {
                    b.HasOne("WebUygulamaProje1.Models.KitapTuru", "kitapTuru")
                        .WithMany()
                        .HasForeignKey("KitapTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kitapTuru");
                });
#pragma warning restore 612, 618
        }
    }
}
